<a href="https://colab.research.google.com/github/ShirinTahmasebi/KTH-ID2223/blob/main/Project/2_reduce_embeddings_dimension.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
RESULT_DATASET_PATH = '/content/drive/MyDrive/Embedding with GPT-3/output/result_Reviews.csv'

In [38]:
engines = \
[
  'text-similarity-davinci-001',
  'text-similarity-ada-001',
  # 'text-similarity-babbage-001',
  # 'text-similarity-curie-001',
  # 'code-search-ada-code-001',
  # 'code-search-babbage-code-001'
]

In [39]:
import pandas as pd

df = pd.read_csv(RESULT_DATASET_PATH, index_col=0)

In [40]:
df

,embedding_text-similarity-davinci-001,reduced_x_text-similarity-davinci-001,reduced_y_text-similarity-davinci-001,embedding_text-similarity-ada-001,reduced_x_text-similarity-ada-001,reduced_y_text-similarity-ada-001,embedding_text-similarity-babbage-001,reduced_x_text-similarity-babbage-001,reduced_y_text-similarity-babbage-001,embedding_text-similarity-curie-001,reduced_x_text-similarity-curie-001,reduced_y_text-similarity-curie-001,embedding_code-search-ada-code-001,reduced_x_code-search-ada-code-001,reduced_y_code-search-ada-code-001,embedding_code-search-babbage-code-001,reduced_x_code-search-babbage-code-001,reduced_y_code-search-babbage-code-001,label
284932,"[-0.005729738622903824, 0.002782381372526288, ...",NaN,NaN,"[0.01860060915350914, -0.015613649971783161, -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
220697,"[-0.015217021107673645, 0.007462559267878532, ...",NaN,NaN,"[0.018258072435855865, 0.03005059063434601, -0...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107908,"[-0.004584628622978926, 0.01346516516059637, -...",NaN,NaN,"[-0.0005673975683748722, -0.012302356772124767...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
107800,"[0.0012591804843395948, 0.00389345595613122, -...",NaN,NaN,"[0.01373705267906189, 0.053661659359931946, -0...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
205313,"[-0.0032210019417107105, 0.0040468997322022915...",NaN,NaN,"[0.021258626133203506, 0.007491868454962969, -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7178,"[-0.0005286579835228622, 0.0024464321322739124...",NaN,NaN,"[-0.016586609184741974, 0.03342374041676521, -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
401972,"[-0.0002831067831721157, -0.003314807778224349...",NaN,NaN,"[-0.016825618222355843, -0.00798442680388689, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
462088,"[-0.0036534518003463745, 0.0004380333120934665...",NaN,NaN,"[0.00622323714196682, 0.008891819044947624, -0...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
267549,"[-0.005907019134610891, 0.0012909695506095886,...",NaN,NaN,"[0.012264199554920197, 0.022083846852183342, -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
542497,"[-0.008624717593193054, 0.004451978951692581, ...",NaN,NaN,"[0.013289941474795341, 0.000356678559910506, -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

In [41]:
import json
from sklearn.manifold import TSNE
import numpy as np

perplexity = 30
tsne_2d = TSNE(n_components=2, verbose=1, perplexity=perplexity, n_iter=3000, random_state=5)

for engine in engines:
  embedding_column_name = 'embedding_' + engine
  reduced_x_column_name = 'reduced_x_' + engine
  reduced_y_column_name = 'reduced_y_' + engine
  
  fetched_embedding_series = df[embedding_column_name].apply(lambda x: json.loads(x))

  fetched_embedding_arr = np.empty((0, len(fetched_embedding_series.iloc[0])), float)
  for item in fetched_embedding_series:
    fetched_embedding_arr = np.append(fetched_embedding_arr, np.array(item).reshape(1, -1), axis=0)
  
  reduced_embeddings = tsne_2d.fit_transform(fetched_embedding_arr)

  reduced_x = reduced_embeddings[:,0]
  reduced_y = reduced_embeddings[:,1]
  
  df[reduced_x_column_name] = reduced_x
  df[reduced_y_column_name] = reduced_y

  # break # Because other embeddings are null so far

/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:783: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:793: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  FutureWarning,

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 1000 samples in 0.010s...
[t-SNE] Computed neighbors for 1000 samples in 0.443s...
[t-SNE] Computed conditional probabilities for sample 1000 / 1000
[t-SNE] Mean sigma: 0.179299
[t-SNE] KL divergence after 250 iterations with early exaggeration: 74.895554
[t-SNE] KL divergence after 3000 iterations: 1.030087

/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:783: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:793: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  FutureWarning,

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 1000 samples in 0.001s...
[t-SNE] Computed neighbors for 1000 samples in 0.074s...
[t-SNE] Computed conditional probabilities for sample 1000 / 1000
[t-SNE] Mean sigma: 0.159884
[t-SNE] KL divergence after 250 iterations with early exaggeration: 75.818832
[t-SNE] KL divergence after 3000 iterations: 1.128529

In [43]:
import os

def check_dir(file_name):
    directory = os.path.dirname(file_name)
    if not os.path.exists(directory):
        os.makedirs(directory)

In [44]:
check_dir('output/result_Reviews.csv')
df.to_csv('output/result_Reviews.csv')

In [45]:
os.system('cp -r "/content/output/" "/content/drive/MyDrive/Embedding with GPT-3/"')

0